import { ArrowLeft, BookOpen, CheckCircle2, Copy, ExternalLink, KeyRound, ShieldCheck, Webhook, Zap } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";

function CopyValue({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  return <button className="icon-button subtle" aria-label={`Copy ${value}`} onClick={() => { navigator.clipboard?.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1400); }}>{copied ? <CheckCircle2 size={14} /> : <Copy size={14} />}</button>;
}

const endpoints = [
  { method: "POST", path: "/api/v1/callbacks/stk", description: "Receive Safaricom STK Push payment confirmations." },
  { method: "POST", path: "/api/v1/callbacks/c2b/confirmation", description: "Receive confirmed C2B transactions." },
  { method: "POST", path: "/api/v1/callbacks/c2b/validation", description: "Validate incoming C2B transactions before completion." },
];

export default function Documentation() {
  const [, navigate] = useLocation();
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand-row"><div className="brand-mark"><Zap size={17} strokeWidth={2.8} /></div><span className="brand-name">LeeTec <span>Engine</span></span></div>
      <div className="workspace-switcher"><div className="workspace-avatar">LT</div><div className="workspace-copy"><strong>LeeTec workspace</strong><span>Production</span></div></div>
      <nav className="nav-area" aria-label="Documentation navigation">
        <div className="nav-group"><div className="nav-label">Developer resources</div>
          <button className="nav-item" onClick={() => navigate("/dashboard")}><ArrowLeft size={17} /><span>Back to workspace</span></button>
          <button className="nav-item active"><BookOpen size={17} /><span>API reference</span></button>
          <button className="nav-item" onClick={() => navigate("/dashboard")}><KeyRound size={17} /><span>API keys</span></button>
          <button className="nav-item" onClick={() => navigate("/dashboard")}><Webhook size={17} /><span>Webhooks</span></button>
        </div>
      </nav>
      <div className="sidebar-bottom"><div className="sandbox-card"><div className="sandbox-icon"><ShieldCheck size={16} /></div><div><strong>Production mode</strong><span>Secure API access</span></div><span className="live-dot" /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span className="slash">/</span><strong>API reference</strong></div><div className="topbar-actions"><Button className="secondary-button" onClick={() => navigate("/dashboard")}><ArrowLeft size={15} /> Workspace</Button></div></header>
      <div className="content-wrap">
        <section className="page-heading"><div><div className="eyebrow">DEVELOPER RESOURCES <span className="eyebrow-line" /></div><h1>API reference</h1><p>Build secure payment flows with LeeTec Engine and Safaricom Daraja.</p></div><div className="heading-actions"><Button className="primary-button" onClick={() => navigate("/dashboard")}><Zap size={16} /> Open workspace</Button></div></section>
        <section className="hero-strip"><div className="hero-copy"><div className="hero-kicker">QUICK START</div><h2>Move from credentials to your first request.</h2><p>Create a production API key, configure your callbacks, and use the endpoint references below to connect your integration.</p></div><div className="hero-art"><BookOpen size={42} /></div></section>
        <div className="settings-grid">
          <section className="settings-card"><div className="settings-card-heading"><div className="settings-icon"><KeyRound size={16} /></div><div><h2>One secret key</h2><p>Use one LeeTec API credential for each user platform.</p></div></div><div className="doc-detail-list"><div><span>Credential format</span><strong>sk_live_…</strong></div><div><span>Accepted header</span><strong>Authorization: Bearer</strong></div><div><span>Alternative header</span><strong>x-api-key</strong></div></div><div className="code-block"><code>Authorization: Bearer sk_live_…</code><CopyValue value="Authorization: Bearer sk_live_" /></div><p className="settings-note"><ShieldCheck size={15} /> Send this secret from your server only. Never expose it in browser or mobile application code.</p></section>
          <section className="settings-card"><div className="settings-card-heading"><div className="settings-icon"><Zap size={16} /></div><div><h2>Payment routing</h2><p>Add a destination in the workspace, then select it when creating a collection.</p></div></div><div className="doc-detail-list"><div><span>Buy Goods</span><strong>Go-Live shortcode + Till number</strong></div><div><span>PayBill</span><strong>PayBill number in both shortcode fields</strong></div><div><span>Transaction type</span><strong>Selected automatically</strong></div></div><p className="settings-note"><ShieldCheck size={15} /> The Daraja production app must be authorized for each destination you add. Wallet top-ups remain routed to the LeeTec platform destination.</p></section>
        </div>
        <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>Server-side STK Push example</h2><p>Call LeeTec from your backend using the secret key generated in the workspace.</p></div><KeyRound size={22} /></div><div className="code-block docs-code-block"><code>{`curl -X POST https://leetec.online/api/v1/stkpush \
  -H "Authorization: Bearer sk_live_your_secret_key" \
  -H "Content-Type: application/json" \
  -d '{"phoneNumber":"254712345678","amount":10,"accountReference":"1ORDER001","transactionDesc":"Customer payment"}'`}</code><CopyValue value={`curl -X POST https://leetec.online/api/v1/stkpush -H "Authorization: Bearer sk_live_your_secret_key" -H "Content-Type: application/json" -d '{"phoneNumber":"254712345678","amount":10,"accountReference":"1ORDER001","transactionDesc":"Customer payment"}'`} /></div><p className="settings-note"><ShieldCheck size={15} /> Keep the key in your server environment, such as <code>LEETEC_API_KEY</code>. LeeTec then handles the Daraja credentials securely.</p></section>
        <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>Node.js integration</h2><p>Use Node.js 18+ and keep the API key in a server environment variable.</p></div><KeyRound size={22} /></div><div className="code-block docs-code-block"><code>{`const response = await fetch("https://leetec.online/api/v1/stkpush", {\n  method: "POST",\n  headers: {\n    Authorization: \`Bearer \${process.env.LEETEC_API_KEY}\`,\n    "Content-Type": "application/json"\n  },\n  body: JSON.stringify({\n    phoneNumber: "254712345678",\n    amount: 10,\n    accountReference: "1ORDER001",\n    transactionDesc: "Customer payment"\n  })\n});\n\nconst result = await response.json();\nif (!response.ok) throw new Error(result.error ?? "STK Push failed");\nconsole.log(result.CheckoutRequestID);`}</code><CopyValue value={`const response = await fetch("https://leetec.online/api/v1/stkpush", { method: "POST", headers: { Authorization: \`Bearer \${process.env.LEETEC_API_KEY}\`, "Content-Type": "application/json" }, body: JSON.stringify({ phoneNumber: "254712345678", amount: 10, accountReference: "1ORDER001", transactionDesc: "Customer payment" }) });`} /></div></section>
        <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>PHP integration</h2><p>Use cURL from your server and read the JSON response before confirming the order.</p></div><KeyRound size={22} /></div><div className="code-block docs-code-block"><code>{`$ch = curl_init("https://leetec.online/api/v1/stkpush");\ncurl_setopt_array($ch, [\n  CURLOPT_POST => true,\n  CURLOPT_HTTPHEADER => [\n    "Authorization: Bearer " . getenv("LEETEC_API_KEY"),\n    "Content-Type: application/json"\n  ],\n  CURLOPT_POSTFIELDS => json_encode([\n    "phoneNumber" => "254712345678",\n    "amount" => 10,\n    "accountReference" => "1ORDER001",\n    "transactionDesc" => "Customer payment"\n  ]),\n  CURLOPT_RETURNTRANSFER => true\n]);\n$body = curl_exec($ch);\n$status = curl_getinfo($ch, CURLINFO_HTTP_CODE);\ncurl_close($ch);\n$result = json_decode($body, true);\nif ($status < 200 || $status >= 300) {\n  throw new RuntimeException($result["error"] ?? "STK Push failed");\n}`}</code><CopyValue value={`curl_init("https://leetec.online/api/v1/stkpush");`} /></div></section>
        <section className="settings-card docs-panel"><div className="settings-card-heading"><div className="settings-icon"><BookOpen size={16} /></div><div><h2>Request and response</h2><p>Use these fields when creating a payment request.</p></div></div><div className="doc-detail-list"><div><span>phoneNumber</span><strong>2547XXXXXXXX</strong></div><div><span>amount</span><strong>Positive amount in KES</strong></div><div><span>accountReference</span><strong>Starts with 1, max 64 characters</strong></div><div><span>transactionDesc</span><strong>Optional payment description</strong></div><div><span>CheckoutRequestID</span><strong>Save the returned payment identifier</strong></div></div><p className="settings-note"><ShieldCheck size={15} /> A successful HTTP response means Safaricom accepted the request. Confirm the final payment status from your LeeTec dashboard before fulfilling an order.</p></section>
        <section className="settings-card docs-panel"><div className="settings-card-heading"><div className="settings-icon"><Webhook size={16} /></div><div><h2>Callbacks and production setup</h2><p>LeeTec manages the Safaricom callback endpoints for the shared production connection.</p></div></div><p className="settings-note">Users do not need to expose their own callback URL or configure Daraja credentials. LeeTec receives the Safaricom callback, validates the payment, and updates the transaction record.</p><div className="doc-detail-list"><div><span>Environment</span><strong>Production</strong></div><div><span>STK type</span><strong>CustomerBuyGoodsOnline</strong></div><div><span>Authentication</span><strong>One sk_live_ secret</strong></div></div></section>
                <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>Callback endpoints</h2><p>Register these public HTTPS endpoints with your payment provider.</p></div><Webhook size={22} /></div><div className="docs-endpoints">{endpoints.map((endpoint) => <div className="docs-endpoint" key={endpoint.path}><span className="method-pill">{endpoint.method}</span><code>{endpoint.path}</code><span>{endpoint.description}</span><ExternalLink size={14} /></div>)}</div></section>
        <section className="settings-card docs-note"><BookOpen size={18} /><div><strong>Need to configure your integration?</strong><p>Open the workspace to create API keys, manage tills, and review wallet and collection activity.</p></div><Button className="secondary-button" onClick={() => navigate("/dashboard")}>Go to workspace</Button></section>
      </div>
    </main>
  </div>;
}
