import { ArrowLeft, BookOpen, CheckCircle2, Copy, KeyRound, ShieldCheck, Webhook, Zap, Code2 as Code2Icon, Activity, AlertTriangle, Database, ExternalLink } from "lucide-react";
import SiteFooter from "@/components/SiteFooter";
import { useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";

function CopyValue({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  return <button className="icon-button subtle" aria-label={`Copy ${value}`} onClick={async () => { try { await navigator.clipboard?.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1400); } catch { setCopied(false); } }}>{copied ? <CheckCircle2 size={14} /> : <Copy size={14} />}</button>;
}

const baseUrl = "https://leetec.online";
const envSnippet = `LEETEC_BASE_URL=https://leetec.online\nLEETEC_API_KEY=sk_live_your_secret_key`;
const curlSnippet = `curl -i -X POST "$LEETEC_BASE_URL/api/v1/stkpush" \\\n  -H "Authorization: Bearer $LEETEC_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{"phoneNumber":"254712345678","amount":10,"accountReference":"1TEST001","transactionDesc":"LeeTec API test","tillId":123}'`;
const nodeSnippet = `const response = await fetch("https://leetec.online/api/v1/stkpush", {\n  method: "POST",\n  headers: {\n    Authorization: \`Bearer \${process.env.LEETEC_API_KEY}\`,\n    "Content-Type": "application/json"\n  },\n  body: JSON.stringify({\n    phoneNumber: "254712345678",\n    amount: 10,\n    accountReference: "1ORDER001",\n    transactionDesc: "Customer payment",\n    tillId: 123\n  })\n});\nconst result = await response.json();\nif (!response.ok) throw new Error(result.error ?? result.message ?? "STK Push failed");\nconsole.log(result.checkoutRequestId, result.status, result.requestRecorded);`;

function CodeBlock({ value }: { value: string }) { return <div className="code-block docs-code-block"><code>{value}</code><CopyValue value={value} /></div>; }
function DetailList({ items }: { items: Array<[string, string]> }) { return <div className="doc-detail-list">{items.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>; }

export default function Documentation() {
  const [, navigate] = useLocation();
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand-row"><div className="brand-mark"><Zap size={17} strokeWidth={2.8} /></div><span className="brand-name">LeeTec <span>Engine</span></span></div>
      <div className="workspace-switcher"><div className="workspace-avatar">LT</div><div className="workspace-copy"><strong>LeeTec Documentation</strong><span>Current API guide</span></div></div>
      <nav className="nav-area" aria-label="Documentation navigation"><div className="nav-group"><div className="nav-label">Developer resources</div><button className="nav-item" onClick={() => navigate("/dashboard")}><ArrowLeft size={17} /><span>Back to workspace</span></button><button className="nav-item active"><BookOpen size={17} /><span>Documentation home</span></button><button className="nav-item" onClick={() => navigate("/dashboard")}><KeyRound size={17} /><span>API keys</span></button><button className="nav-item" onClick={() => navigate("/dashboard")}><Webhook size={17} /><span>Webhooks</span></button></div></nav>
      <div className="sidebar-bottom"><div className="sandbox-card"><div className="sandbox-icon"><ShieldCheck size={16} /></div><div><strong>Production ready</strong><span>HTTPS API access</span></div><span className="live-dot" /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span className="slash">/</span><strong>API reference</strong></div><div className="topbar-actions"><Button className="secondary-button" onClick={() => navigate("/dashboard")}><ArrowLeft size={15} /> Workspace</Button></div></header>
      <div className="content-wrap">
        <section className="page-heading"><div><div className="eyebrow">DEVELOPER RESOURCES <span className="eyebrow-line" /></div><h1>LeeTec API documentation</h1><p>Current guidance for secure M-PESA STK Push, C2B collections, complete payment history, and optional webhooks.</p></div><div className="heading-actions"><Button className="primary-button" onClick={() => navigate("/dashboard")}><Zap size={16} /> Open workspace</Button></div></section>
        <section className="hero-strip"><div className="hero-copy"><div className="hero-kicker">QUICK START</div><h2>Send a request, track every outcome.</h2><p>Create an API key, call LeeTec from your backend, then read the authoritative status from transaction history. Webhooks are optional notifications—not a requirement for payment visibility.</p></div><div className="hero-art"><Activity size={42} /></div></section>

        <div className="settings-grid">
          <section className="settings-card"><div className="settings-card-heading"><div className="settings-icon"><KeyRound size={16} /></div><div><h2>API authentication</h2><p>Use a recoverable secret from Workspace → API keys.</p></div></div><DetailList items={[["Credential format", "sk_live_…"], ["Primary header", "Authorization: Bearer"], ["Alternative header", "x-api-key"], ["Secret storage", "Encrypted owner-only recovery"]]} /><p className="settings-note"><ShieldCheck size={15} /> Keep the key on your server only. Never put it in browser, mobile, or public source code.</p></section>
          <section className="settings-card"><div className="settings-card-heading"><div className="settings-icon"><Zap size={16} /></div><div><h2>LeeTec handles the payment connection</h2><p>You only integrate with the public API.</p></div></div><DetailList items={[["Base URL", baseUrl], ["Credentials", "Managed by LeeTec"], ["Callbacks", "Managed by LeeTec"], ["Payment routing", "Configured for your workspace"]]} /><p className="settings-note"><ShieldCheck size={15} /> You do not need Daraja credentials, database settings, or callback infrastructure. Use your LeeTec API key and the public API contract.</p></section>
        </div>

        <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>Copyable STK Push request</h2><p>A successful response means the request was accepted and recorded as pending.</p></div><Code2Icon /></div><CodeBlock value={curlSnippet} /><p className="settings-note"><Activity size={15} /> Save <code>checkoutRequestId</code>. The response includes <code>status: "PENDING"</code> and <code>requestRecorded: true</code>. Do not fulfill an order until history reports <code>SUCCESS</code> with a receipt.</p></section>
        <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>Node.js server example</h2><p>Use Node.js 18+ or any backend runtime that can make HTTPS requests.</p></div><Code2Icon /></div><CodeBlock value={nodeSnippet} /></section>

        <div className="settings-grid">
          <section className="settings-card docs-panel"><div className="settings-card-heading"><div className="settings-icon"><BookOpen size={16} /></div><div><h2>Request fields</h2><p>Validation applied by the API.</p></div></div><DetailList items={[["phoneNumber", "254XXXXXXXXX, 07XXXXXXXX, or 01XXXXXXXX"], ["amount", "Positive KES amount, max 1,500,000"], ["accountReference", "Starts with 1, max 64 characters"], ["transactionDesc", "Optional, max 100 characters"], ["tillId", "Optional active workspace destination"]]} /></section>
          <section className="settings-card docs-panel"><div className="settings-card-heading"><div className="settings-icon"><AlertTriangle size={16} /></div><div><h2>Payment lifecycle</h2><p>Every accepted request remains visible.</p></div></div><DetailList items={[["PENDING", "Daraja accepted; awaiting customer callback"], ["SUCCESS", "Receipt validated; payment confirmed"], ["FAILED", "Rejected, timed out, invalid, or mismatched"], ["CANCELLED", "Customer cancelled the prompt"], ["ERROR", "API rejected before Daraja acceptance"]]} /></section>
        </div>

        <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>Complete payment history</h2><p>All routes return the authenticated account's complete newest-first dataset.</p></div><Activity size={22} /></div><div className="docs-endpoints"><div className="docs-endpoint"><span className="method-pill">GET</span><code>/api/v1/transactions</code><span>Complete collections, payouts, and wallet deposits.</span></div><div className="docs-endpoint"><span className="method-pill">GET</span><code>/api/v1/stkpush/history</code><span>Alias for the same complete authenticated history.</span></div><div className="docs-endpoint"><span className="method-pill">GET</span><code>/api/v1/collections</code><span>Alias for the same complete authenticated history.</span></div></div><p className="settings-note"><ShieldCheck size={15} /> History preserves pending, successful, failed, and cancelled records. Responses use <code>Cache-Control: no-store</code> and include <code>requestId</code>, <code>resourceType</code>, and <code>final</code>.</p></section>

        <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>Webhooks are optional</h2><p>Use them for push notifications while polling history remains authoritative.</p></div><Webhook size={22} /></div><DetailList items={[["Setup", "Workspace → Webhooks"], ["Events", "payment.success, payment.failed, payment.cancelled"], ["Signature", "X-LeeTec-Signature: sha256=..."], ["Delivery", "Three attempts; final result logged"], ["Test", "Use Test delivery and require a 2xx response"]]} /><CodeBlock value={`Content-Type: application/json\nUser-Agent: LeeTec-Webhook/1.0\nX-LeeTec-Event: payment.success\nX-LeeTec-Delivery: <unique-id>\nX-LeeTec-Signature: sha256=<hex-hmac>`} /><p className="settings-note"><ShieldCheck size={15} /> Verify the HMAC against the exact raw body, deduplicate by delivery ID, respond quickly with 2xx, and process asynchronously. Payment history still works when no webhook is configured.</p></section>

        <section className="settings-grid"><section className="settings-card docs-panel"><div className="settings-card-heading"><div className="settings-icon"><CheckCircle2 size={16} /></div><div><h2>Consumer integration checklist</h2><p>Everything required on your side.</p></div></div><DetailList items={[["1", "Create or receive a LeeTec API key"], ["2", "Store it only on your backend"], ["3", "Send requests over HTTPS"], ["4", "Save the returned request ID"], ["5", "Read history until final status"], ["6", "Fulfill only validated SUCCESS payments"]]} /></section><section className="settings-card docs-panel"><div className="settings-card-heading"><div className="settings-icon"><ShieldCheck size={16} /></div><div><h2>What you do not configure</h2><p>LeeTec operates these services for you.</p></div></div><DetailList items={[["Daraja credentials", "Managed by LeeTec"], ["Database and ledger", "Managed by LeeTec"], ["Safaricom callbacks", "Managed by LeeTec"], ["Payment routing", "Configured in your LeeTec workspace"]]} /></section></section>
        <section className="admin-panel docs-panel"><div className="admin-panel-heading"><div><h2>Support and workspace actions</h2><p>Manage keys, destinations, webhooks, and full history from the authenticated workspace.</p></div><ExternalLink size={22} /></div><div className="modal-actions"><Button className="primary-button" onClick={() => navigate("/dashboard")}><KeyRound size={15} /> Manage API keys</Button><Button className="secondary-button" onClick={() => navigate("/dashboard")}><Webhook size={15} /> Configure webhooks</Button></div></section>
        <SiteFooter />
      </div>
    </main>
  </div>;
}
