import { ArrowLeft, ArrowRight, CheckCircle2, Mail, XCircle, Zap } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function ForgotPassword() {
  const [, navigate] = useLocation();
  const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const response = await fetch("/api/auth/forgot-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Unable to process password reset."); setNotice(body.message); } catch (err) { setError(err instanceof Error ? err.message : "Unable to process password reset."); } finally { setBusy(false); } };
  return <div className="login-page"><div className="login-ambient ambient-one" /><div className="login-ambient ambient-two" /><form className="login-card login-card-upgraded" onSubmit={submit}><button type="button" className="auth-home-link" onClick={() => navigate("/login")}><ArrowLeft size={14} /> Back to sign in</button><div className="login-logo"><div className="brand-mark"><Zap size={18} /></div><span className="brand-name">LeeTec <span>Engine</span></span></div><div className="login-icon"><Mail size={21} /></div><span className="auth-mode-label">ACCOUNT SECURITY</span><h1>Reset your password.</h1><p>Enter your account email and we will send a secure, one-time reset link if the account exists.</p><Input autoComplete="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email address" aria-label="Email address" required />{error && <div className="login-error"><XCircle size={15} /> <span>{error}</span></div>}{notice && <div className="login-success"><CheckCircle2 size={15} /> <span>{notice}</span></div>}<Button type="submit" disabled={busy} className="primary-button login-button">{busy ? "Sending…" : "Send reset link"} {!busy && <ArrowRight size={16} />}</Button><button type="button" className="login-switch" onClick={() => navigate("/login")}>Remembered your password? Sign in</button><div className="login-foot"><span><span className="live-dot" /> One-time secure link</span><span>Expires in 30 minutes</span></div></form></div>;
}
