import { ArrowRight, CheckCircle2, Code2, CreditCard, Github, ShieldCheck, Sparkles, Terminal, Zap } from "lucide-react";
import { useEffect } from "react";
import { useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";

const features = [
  { icon: CreditCard, title: "Collect with STK Push", copy: "Launch reliable M-PESA collections with clean callbacks and clear transaction status." },
  { icon: Terminal, title: "Ship with the LeeTec API", copy: "Use API keys, webhooks, and a predictable REST layer built for fast-moving payment teams." },
  { icon: ShieldCheck, title: "Built for control", copy: "Keep wallet activity, Till payments, and developer access visible from one secure workspace." },
];

export default function Landing() {
  const [, navigate] = useLocation();
  const { user, loading } = useAuth();
  useEffect(() => { if (!loading && user) navigate(user.role?.toUpperCase() === "ADMIN" ? "/admin" : "/dashboard"); }, [loading, user, navigate]);
  return <main className="landing-page">
    <header className="landing-nav">
      <button className="landing-brand" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><span className="brand-mark"><Zap size={17} strokeWidth={2.8} /></span><span className="brand-name">LeeTec <em>Engine</em></span></button>
      <nav><a href="#platform">Platform</a><a href="#developers">Developers</a><a href="#api">API access</a><a href="#security">Security</a></nav>
      <div className="landing-actions"><button className="landing-docs" onClick={() => navigate("/docs")}>API docs <ArrowRight size={13} /></button><button className="landing-login" onClick={() => navigate("/login")}>Sign in</button><Button className="primary-button" onClick={() => navigate("/login?mode=register")}>Create account <ArrowRight size={15} /></Button></div>
    </header>
    <section className="landing-hero"><div className="landing-hero-copy"><div className="landing-eyebrow"><span className="live-dot" /> M-PESA infrastructure for ambitious teams</div><h1>Move money.<br /><span>Build momentum.</span></h1><p>LeeTec Engine is the developer-first payment layer for Kenyan businesses. Collect through STK Push, connect webhooks, and keep every transaction visible from one secure workspace.</p><div className="landing-hero-actions"><Button className="primary-button landing-cta" onClick={() => navigate("/login?mode=register")}>Start building <ArrowRight size={17} /></Button><button className="landing-secondary" onClick={() => navigate("/docs")}>Explore the API <span>↗</span></button></div><div className="landing-proof"><div className="proof-avatars"><span>BK</span><span>AW</span><span>DO</span></div><span><strong>Built for payment teams</strong><small>Secure workspace access with optional email verification</small></span></div></div><div className="landing-console"><div className="console-glow" /><div className="console-top"><span><span className="console-dot green" /><span className="console-dot yellow" /><span className="console-dot red" /></span><span>leetec / payments</span><span className="console-live"><span className="live-dot" /> live</span></div><div className="console-body"><div className="console-label">TODAY'S PROCESSING</div><div className="console-amount">KES 611,370<span>.00</span></div><div className="console-chart">{[34, 48, 40, 58, 52, 72, 64, 80, 70, 91, 76, 88].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div><div className="console-row"><span><CheckCircle2 size={14} /> 98.7% success rate</span><span>Last 30 days ↗</span></div><div className="console-events"><div><span className="event-icon lime"><CreditCard size={13} /></span><span><strong>STK Push completed</strong><small>254 712 884 203 · just now</small></span><b>+ KES 2,500</b></div><div><span className="event-icon purple"><Code2 size={13} /></span><span><strong>Webhook delivered</strong><small>payment.completed · 200 OK</small></span><b>Delivered</b></div></div></div></div></section>
    <section id="platform" className="landing-section"><div className="section-heading"><div><span className="landing-eyebrow">ONE CONTROL PLANE <i /></span><h2>Everything your money flows need.</h2></div><p>From your first API call to your millionth transaction, stay close to every detail that matters.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, copy }) => <article className="feature-card" key={title}><span className="feature-icon"><Icon size={19} /></span><h3>{title}</h3><p>{copy}</p><span className="feature-link">Explore capability <ArrowRight size={14} /></span></article>)}</div></section>
    <section id="api" className="landing-api-band"><div><span className="landing-eyebrow"><Code2 size={13} /> API-FIRST PAYMENTS</span><h2>One clean API.<br /><span>Every payment visible.</span></h2></div><div><p>Authenticate with one server-side API key, send STK Push requests, receive verified webhook events, and confirm outcomes in the LeeTec workspace.</p><button className="landing-secondary" onClick={() => navigate("/docs")}>Read the API reference <ArrowRight size={14} /></button></div></section>
    <section id="developers" className="landing-band"><div><span className="landing-eyebrow"><Sparkles size={13} /> DEVELOPER FIRST</span><h2>Less plumbing.<br /><span>More progress.</span></h2></div><div className="landing-band-copy"><p>Get the visibility of a mature payments stack without the overhead. Create your workspace and start building in minutes; email verification remains available later.</p><div className="landing-checks"><span><CheckCircle2 size={15} /> REST APIs & webhooks</span><span><CheckCircle2 size={15} /> Turso-backed reliability</span><span><CheckCircle2 size={15} /> Optional email verification</span></div></div></section>
    <footer id="security" className="landing-footer"><div className="landing-brand"><span className="brand-mark"><Zap size={17} /></span><span className="brand-name">LeeTec <em>Engine</em></span></div><span>Secure M-PESA infrastructure for modern businesses.</span><div><button onClick={() => navigate("/docs")}>API docs</button><button onClick={() => navigate("/login")}>Sign in</button><button onClick={() => navigate("/login?mode=register")}>Create account</button><Github size={16} /></div></footer>
  </main>;
}
