import { ArrowLeft, ArrowRight, CheckCircle2, Eye, EyeOff, LockKeyhole, XCircle, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function ResetPassword() {
  const [, navigate] = useLocation(); const token = new URLSearchParams(window.location.search).get("token") || "";
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const checks = useMemo(() => ({ length: password.length >= 8, upper: /[A-Z]/.test(password), number: /\d/.test(password), match: password.length > 0 && password === confirm }), [password, confirm]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setNotice(""); if (!token) return setError("This password reset link is invalid or expired."); if (!checks.length || !checks.upper || !checks.number) return setError("Password must be at least 8 characters and include an uppercase letter and a number."); if (!checks.match) return setError("Passwords do not match."); setBusy(true); try { const response = await fetch("/api/auth/reset-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Unable to reset password."); navigate("/login?reset=1"); } catch (err) { setError(err instanceof Error ? err.message : "Unable to reset password."); } finally { setBusy(false); } };
  return <div className="login-page"><div className="login-ambient ambient-one" /><div className="login-ambient ambient-two" /><form className="login-card login-card-upgraded" onSubmit={submit}><button type="button" className="auth-home-link" onClick={() => navigate("/login")}><ArrowLeft size={14} /> Back to sign in</button><div className="login-logo"><div className="brand-mark"><Zap size={18} /></div><span className="brand-name">LeeTec <span>Engine</span></span></div><div className="login-icon"><LockKeyhole size={21} /></div><span className="auth-mode-label">ACCOUNT SECURITY</span><h1>Create a new password.</h1><p>Use a strong password to keep your LeeTec workspace protected.</p><div className="password-wrap"><Input autoComplete="new-password" type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="New password" aria-label="New password" required /><button type="button" className="password-toggle" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff size={16} /> : <Eye size={16} />}</button></div><div className="password-wrap"><Input autoComplete="new-password" type={show ? "text" : "password"} value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Confirm new password" aria-label="Confirm new password" required /><span className="password-confirm-icon">{checks.match ? <CheckCircle2 size={15} /> : confirm ? <XCircle size={15} /> : null}</span></div><div className="password-rules"><span className={checks.length ? "valid" : ""}>8+ characters</span><span className={checks.upper ? "valid" : ""}>One uppercase</span><span className={checks.number ? "valid" : ""}>One number</span></div>{error && <div className="login-error"><XCircle size={15} /> <span>{error}</span></div>}<Button type="submit" disabled={busy} className="primary-button login-button">{busy ? "Updating…" : "Update password"} {!busy && <ArrowRight size={16} />}</Button><div className="login-foot"><span><span className="live-dot" /> One-time secure link</span><span>Expires in 30 minutes</span></div></form></div>;
}
